ExtendRealityLtd/Zinnia.Unity

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/SUPPORT.md
- .gitignore
- README.md
The default set of GitHub docs has been added to provide automated
links within GitHub to important information.
The `README.md` has been updated to contain basic information for the
moment and a `.gitignore` file has been added to ignore basic system
files.
> chore(Structure): add default github documentation and standard readme

- LICENSE.meta
- Prefabs.meta
- Prefabs/[UnityXRCameraRig].meta
- Prefabs/[UnityXRCameraRig]/[UnityXRCameraRig].prefab
- Prefabs/[UnityXRCameraRig]/[UnityXRCameraRig].prefab.meta
- README.md.meta
The UnityXR camera rig prefab provides a base set up for using a
VR setup with a tracked HMD and tracked left/right controllers
utilising the built in UnityXR functionality.
> feat(Prefabs): default UnityXR camera rig prefab

- Resources.meta
- Resources/Materials.meta
- Resources/Materials/CameraColorOverlay.mat
- Resources/Materials/CameraColorOverlay.mat.meta
- Resources/Shaders.meta
- Resources/Shaders/Unlit_TransparentColor.shader
- Resources/Shaders/Unlit_TransparentColor.shader.meta
- Scripts/Visual.meta
- Scripts/Visual/CameraColorOverlay.cs
- Scripts/Visual/CameraColorOverlay.cs.meta
The Camera Color Overlay script can be used to fade the color on a
selection of cameras to a new color, which can be useful for fading
the viewpoint or emulating a blink for such things as teleporting.
> feat(Visual): add camera color overlay - fixes #5

- Scripts/Tracking/Follow/ObjectFollow.cs
- Scripts/Tracking/TransformModify.cs
- Scripts/Visual/CameraColorOverlay.cs
If UnityEvents aren't instantiated at the point of creation then they
will throw a null reference exception if they are referenced via code
e.g. if trying to add a listener to an event via code.
They don't do this in the editor because the editor instantiates the
event type when a new persistent event is added.
> fix(events): ensure all UnityEvents are instantiated to prevent nulls

- Tests/Editor/Tracking/Follow/Modifier/TransformSourceFollowActiveTargetTest.cs
- Tests/Editor/Tracking/Follow/Modifier/TransformTargetsFollowSourceTest.cs
- Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
- Tests/Editor/Tracking/TransformModifyTest.cs
- Tests/Editor/Tracking/Velocity/VelocityEstimatorTest.cs
- Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
Instead of simply setting created scene objects to `null` in the
teardown on the tests, it's better to call `DestroyImmediate` as this
will ensure the object is destroyed promptly and garbage can be
collected appropriately.
> fix(tests): call DestroyImmediate in teardown for created scene objects

- Scripts/Tracking/GameObjectStateMirror.cs
- Scripts/Tracking/GameObjectStateMirror.cs.meta
- Tests/Editor/Tracking/GameObjectStateMirrorTest.cs
- Tests/Editor/Tracking/GameObjectStateMirrorTest.cs.meta
The GameObjectStateMirror allows for a source GameObject active state
to control the active states of a collection of target GameObjects.
As it is a Process it requires to be added to a MomentProcessor to
execute.
> feat(Tracking): mirror game object active state to other game objects

- Scripts/Tracking/XrDeviceRelationActivator.cs
- Scripts/Tracking/XrDeviceRelationActivator.cs.meta
- Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
- Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs.meta
Supporting multiple devices and SDKs results in the need to activate
and deactivate device/SDK specific game objects like the camera
rigs. The `XrDeviceRelationActivator` added with this change allows
to specify a mapping from XR device name to game objects using a new
type `XrDeviceRelation` which are then automatically (de)activated
based on the currently loaded XR device in Unity. The activator
additionally allows to deactivate all relations or activate a
specific one manually.
> feat(XrRelation): (de)activating game objects based on XR device - resolves #13

- Scripts/Visual/CameraColorOverlay.cs
The `AddColorOverlay` method will now ignore any subsequent calls of
it with the same parameters within the same frame.
This prevents such things as emitting the event multiple times even
if the method is called multiple times with the same information.
> fix(Visual): prevent add from being called twice with same parameters

- Scripts/Tracking/CollisionTracker.cs
- Scripts/Tracking/CollisionTracker.cs.meta
To track whether a collision between to objects happens Unity offers
so called "Messages" which are defined methods that are not part of
the inheritance chain. This change adds a new component
`CollisionTracker` that allows to forward any of these messages via
UnityEvents. The events differentiate between a trigger and non-
trigger collision and the event data allows retrieving that
information in addition to the collision and the collider.
> feat(Tracking): collision tracking

- Prefabs/Pointers/ObjectPointer.Parabolic.Solid.prefab
- Prefabs/Pointers/ObjectPointer.Straight.Solid.prefab
The Follow Modifier structure was changed and scripts removed meaning
the Pointer prefabs were using deleted scripts. This fixes the issue
by applying the new script structure to the prefabs.
> fix(Pointer): update prefabs to use new follow modifier structure

- .github/CONTRIBUTING.md
- Prefabs/Locomotion/Teleporters/Scripts/TeleporterInternalSetup.cs
- Scripts/Action/CompoundAndAction.cs
- Scripts/Extension/IEnumerableExtensions.cs
- Scripts/Extension/IEnumerableExtensions.cs.meta
- Scripts/Process/MomentProcessor.cs
- Scripts/Process/SourceTargetProcessor.cs
- Scripts/Tracking/Velocity/VelocityTrackerProcessor.cs
- Scripts/Tracking/XrDeviceRelationActivator.cs
- Tests/Editor/Action/CompoundAndActionTest.cs
- Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
- Tests/Editor/Tracking/GameObjectStateMirrorTest.cs
- Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
- Tests/Editor/Tracking/XrDeviceRelationActivatorTest.cs
It is better to use a `List` type than an array for a public field as
a List comes with easier helper methods to add and remove (or clear)
items from the List. This means if someone is trying to update the List
contents via script at runtime, they don't need to mess about with an
array structure to add or remove items.
A new `IEnumerableExtensions` component has been added that adds a new
method to any `IEnumerable` type (e.g. `List`) called `EmptyIfNull`
and will return an instantiated empty `List` if the variable is null.
This will prevent null exceptions when accessing the variable in
situations like `foreach` loops.
> refactor(Structure): favour List types over arrays for public fields

- Scripts/Visual/CameraColorOverlay.cs
- Tests/Editor/Visual/CameraColorOverlayTest.cs
There is no need to name an event after the type it is a member of.
This changes the `CameraColorOverlay` to use the proper event naming
convention that is used everywhere else.
> chore(Visual): rename camera overlay events

- Scripts/Cast/PointsCast.cs
- Scripts/Pointer/ObjectPointer.cs
- Scripts/Tracking/CollisionTracker.cs
- Scripts/Tracking/Follow/ObjectFollow.cs
- Scripts/Tracking/TransformModify.cs
- Scripts/Visual/CameraColorOverlay.cs
As event data payloads are the same instance that is just mutated each
time the event is emitted, this means any listener that digests the
event should not attempt to mutate the event data otherwise it will
change the original reference.
Therefore, a new EventData payload should be instantiated and be a
new instance to prevent overriding the original data.
This is achieved by a new `Set` method that accepts the `EventData`
as the parameter and a new `Clear` method that resets the data
back to the default values.
> fix(events): ensure digested event data is not mutated

- Scripts/Tracking/CollisionTracker.cs
The `CollisionTracker` followed Unity's physics message method names
for its event names. This change renames all events to follow the
code conventions and merges the collision and trigger events to only
leave the collision ones. Additionally a new flags enum allows to
select which collision types to emit the events for.
> chore(Tracking): collision tracker events

- Scripts/Tracking/Velocity/VelocityEstimator.cs
- Scripts/Tracking/Velocity/VelocityTracker.cs
- Scripts/Tracking/Velocity/VelocityTrackerProcessor.cs
- Tests/Editor/Tracking/Velocity/VelocityTrackerProcessorTest.cs
The Velocity Estimator concrete classes always made a call to
`IsActive` but this logic is consistent across all sub classes so
it has now been moved into the base class and the public methods
are no longer abstract, instead the implementation is a protected
method that is abstract and requires overriding.
> refactor(Velocity): move common calls into base class

- Scripts/Tracking/Follow/Modifier/FollowModifier.cs
- Scripts/Tracking/Follow/Modifier/ModifyRigidbodyVelocity.cs
- Scripts/Tracking/Follow/Modifier/ModifyTransform.cs
- Scripts/Tracking/Follow/Modifier/SourceFollowActiveTarget.cs
- Scripts/Tracking/Follow/Modifier/TargetsFollowSource.cs
- Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
There were a number of places where the same logic in different
FollowModifier components was being repeated, such as the caching
of the transforms.
This has all now been moved into the base class so the extended
classes can focus on exactly what they're meant to do and not worry
about the caching.
> refactor(Follow): reduce duplicate code in follow modifiers

- Scripts/Tracking/CollisionTracker.cs
The UnityFlags attribute was recently updated but the CollisionTracker
component was still using the old UnityFlag attribute.
> fix(Tracking): update enum attribute to UnityFlags in collision tracker

- Scripts/Tracking/CollisionTracker.cs
The `CollisionTracker` recently changed to have a member that allows
to specify for which types of collisions the events will be emitted
for but it was never correctly checked against.
> fix(Tracking): add missing collision tracker type check

- Tests/Editor/Tracking/Follow/Modifier/ModifyRigidbodyVelocityTest.cs
- Tests/Utility/TimeSettingOverride.cs
- Tests/Utility/TimeSettingOverride.cs.meta
Tests that rely on rigidbody information require explicit Unity time
settings otherwise the settings will affect the test results.
This has been fixed by providing a new test utility that can set the
time settings and then reset them back to the previous settings to
allow tests to run in the correct time state.
> fix(Tracking): explicitly specify time settings for rigidbody tests

- Scripts/Tracking/Velocity/VelocityEstimator.cs
The local position and local rotation used in calculations of
velocity estimations has now been replaced with global position
and global rotation as this provides a better global solution
to estimating velocities on all objects not just top level objects.
> fix(Velocity): use global space instead of local for calculations - fixes #119

- Scripts/Data/Attribute/Editor/MinMaxRangeDrawer.cs
- Scripts/Data/Attribute/Editor/UnityFlagsDrawer.cs
- Scripts/Data/Type/Editor/FloatRangeDrawer.cs
- Scripts/Data/Type/Editor/Vector3StateDrawer.cs
By default Unity shows values that are part of a prefab instance
differently in case that value is changed compared to the prefab's
default value. This change ensures that Unity does the same to all
of the custom drawers.
> chore(Editor): ensure prefab changes are shown - resolves #159

- Scripts/Tracking/Modification/DirectionModifier.cs
The DirectionModifier could throw errors in certain edge cases as the
use of the GameObject references for target and pivot were not always
checked for null status before being used.
This fix ensures they are always prior checked and the checks have been
moved to more appropriate places to ensure cleaner code.
> fix(Modification): ensure references are not null before acting on them

- Scripts/Tracking/Follow/Modifier/Property/Rotation/RigidbodyForceAtPosition.cs
- Scripts/Tracking/Follow/Modifier/Property/Rotation/RigidbodyForceAtPosition.cs.meta
A new follow modifier property dealing with rotation has been added
that applies a force at a given position to a rigidbody which creates
a torque providing a rotation to the object.
This is useful for controlling objects that are attached on a hinge
joint.
As this is using actual forces it cannot be tested via the editor
tests.
> feat(Follow): add rigidbody rotation by force follow modifier property

- Scripts/Tracking/Modification/DirectionModifier.cs
- Tests/Editor/Tracking/Modification/DirectionModifierTest.cs
The DirectionModifier can now have the look at target prevented from
applying z axis rotation to the grabbed object. This can provide a
more natural direction control in certain circumstances.
This solution is taken from VRTK v3 and was based largely on the
solution provided by @DrHibbitts
> feat(Modification): option to lock look at z axis rotation

- Scripts/Rule/RulesMatcher.cs
- Scripts/Rule/RulesMatcher.cs.meta
- Tests/Editor/Rule/RulesMatcherTest.cs
- Tests/Editor/Rule/RulesMatcherTest.cs.meta
The RulesMatcher allows a for a List of rules to be provided with
an associated event for each rule. When the `Match` method is called
with a source GameObject, any rule in the list that matches based
on the given GameObject will emit the associated event.
> feat(Rule): match against a collection of rules and emit event

- Prefabs/CameraRig/TrackedAlias/SharedResources/Scripts/TrackedAliasFacade.cs
- Prefabs/CameraRig/TrackedAlias/SharedResources/Scripts/TrackedAliasInternalSetup.cs
- Prefabs/CameraRig/TrackedAlias/[VRTK_TrackedAlias].prefab
The TrackedAlias prefab has internal events to know when the relevant
alias elements have begun tracking, these are now exposed to the facade
so it is easier to wire up actions on these events without needing to
go into the underlying structure.
> feat(CameraRig): expose alias tracking begun events

- Prefabs/CameraRig/SimulatedCameraRig/[SimulatedCameraRig].prefab
- Scripts/Data/Type/Transformation/Vector2Multiplier.cs
The Vector2Multiplier was using two floats as the multiplier to use
in the operation this type implements. A Vector2 is a better
replacement for those floats and supports the same operations. The
existing setter methods are kept so per-axis changes are possible
via Editor inspectors while this change additionally allows
specifying a Vector2 directly.
> fix(Transformation): use vector multiplier

- Prefabs/Interactions/Interactables/SharedResources/Scripts/GrabInteractableInternalSetup.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/TouchInteractableInternalSetup.cs
- Prefabs/Interactions/Interactors/SharedResources/Scripts/GrabInteractorInternalSetup.cs
- Prefabs/Interactions/Interactors/SharedResources/Scripts/InteractorFacade.cs
- Scripts/Tracking/Collision/Active/ActiveCollisionPublisher.cs
The InteractorFacade now has a Grab and Ungrab helper method that
allows an Interactable to be passed to a specific Interactor to
initiate a grab (or alternatively ungrab).
This makes it possible to initiate a grab/ungrab from either the
Interactor or the Interactable.
> feat(Interaction): add grab/ungrab helper methods to interactors

- Prefabs/CameraRig/UnityXRCameraRig/SharedResources/Scripts/UnityXRConfiguration.cs
The configuration component for the Unity XR settings was changing
the project time settings while in the editor and not playing. Since
the XR device is not loaded at edit-time this resulted in wrong time
settings. The fix is to only run the setting logic when playing.
> fix(CameraRig): don't change time settings at edit-time

- Prefabs/Interactions/Interactables/Interactable.Climbable.prefab
- Prefabs/Interactions/Interactables/Interactable.Touchable.Grabbable.DirectionControllable.prefab
- Prefabs/Interactions/Interactables/Interactable.Touchable.Grabbable.Scalable.prefab
- Prefabs/Interactions/Interactables/Interactable.Touchable.Grabbable.Swappable.prefab
- Prefabs/Interactions/Interactables/Interactable.Touchable.Grabbable.prefab
- Prefabs/Interactions/Interactables/SharedResources/Scripts/GrabInteractableInternalSetup.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/TouchInteractableInternalSetup.cs
The first/last-Touch/Grab methods used to be public and would be
called from the prefab events. However, this meant that the prefab
would need to always be set up to call these intrinsic events whereas
the touch/untouch grab/ungrab methods can always know when to call
the first/last events and always know to do it in the right order
therefore avoiding any prefab configuration issues.
The Climbable prefab was not recognising grabbed interactors because
the script relied upon there being a GameObjectStack but the Climbable
interactor didn't utilize one. This has now been updated so the
Climbable uses the GameObjectSet and the internal grab setup script
can choose between either using a provided GameObjectStack or if that
is not provided then the provided GameObjectSet.
The GameObjectSet is …
> feat(Interactions): perform first/last touch/grab in script

- Prefabs/CameraRig/SimulatedCameraRig/SharedResources/Scripts/SimulatorConfiguration.cs
- Prefabs/CameraRig/TrackedAlias/SharedResources/Scripts/TrackedAliasInternalSetup.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/GrabInteractableInternalSetup.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/InteractableFacade.cs
- Prefabs/Interactions/Interactables/SharedResources/Scripts/TouchInteractableInternalSetup.cs
- Prefabs/Interactions/Interactors/SharedResources/Scripts/GrabInteractorInternalSetup.cs
- Prefabs/Interactions/Interactors/SharedResources/Scripts/InteractorFacade.cs
- Prefabs/Interactions/Interactors/SharedResources/Scripts/TouchInteractorInternalSetup.cs
- Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterFacade.cs
- Scripts/Tracking/Collision/Active/Operation/NotifierContainerExtractor.cs
- Scripts/Tracking/Follow/Modifier/FollowModifier.cs
- Scripts/Tracking/Follow/ObjectFollower.cs
Monadic null checking was introduced in C#6 and means that objects
don't need an `if (x == null)` check and can simply do `x?.` to
determine if the object is null. However, as Unity bypasses the
standard operators and checks, this means the monadic null check
does not work with Unity MonoBehaviour scripts along with GameObject
and Transform objects so any use of `?.` will not produce the
expected results.
This fix removes any misuse of the monadic null check.
> fix(Structure): remove erroneous uses of monadic null checks - fixes #175

- Prefabs/Interactions/Interactors/SharedResources/Scripts/TouchInteractorInternalSetup.cs
- Scripts/Tracking/Collision/Active/ActiveCollisionPublisher.cs
The Untouch event on an Interactor was not being emitted when the
Interactor became disabled due to the collider not actually calling
the Collision/Trigger exit code.
The solution is to copy the current touching objects to the stop
touching collision list and force publish it to tell any existing
touched item that it is no longer being touched.
To achieve the publish, a new Force method has been added as the
normal methods only operate when the Interactor is active and enabled
and it will not execute those methods in OnDisable.
> fix(Interactions): publish untouch when interactor is disabled

- Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterInternalSetup.cs
- Scripts/Tracking/Collision/Active/Operation/NotifierContainerExtractor.cs
- Scripts/Tracking/Follow/Modifier/FollowModifier.cs
Since the monadic null checks were removed, a number of scripts would
fail due to null data trying to be processed. These have now been
fixed with an explicit `x == null` check.
> fix(Structure): alternative null checks for removed monadic checks

- Prefabs/CameraRig/SimulatedCameraRig/[SimulatedCameraRig].prefab
- Prefabs/CameraRig/UnityXRCameraRig/[UnityXRCameraRig].prefab
- Scripts/Extension/GameObjectExtensions.cs
- Scripts/Tracking/Velocity/VelocityEstimator.cs
- Tests/Editor/Extension/GameObjectExtensionsTest.cs
The VelocityEstimator now allows for a relativeTo GameObject that
can be used to determine a relative velocity rather than a global
velocity.
This is useful if the tracked object is also being moved due to
a parent object being moved.
The CameraRig prefabs have been updated so the controller velocity
is always tracked relative to the parent play area.
> feat(Velocity): calculate with optional relative to object - fixes #197

- Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterFacade.cs
- Prefabs/Locomotion/Teleporters/SharedResources/Scripts/TeleporterInternalSetup.cs
- Prefabs/Locomotion/Teleporters/Teleporter.Dash.SnapToFloor.prefab
- Prefabs/Locomotion/Teleporters/Teleporter.Instant.SnapToFloor.prefab
The Teleporter would previously always apply an offset of the
HeadsetAlias to the PlayAreaAlias when moving it but there can be
instances where the PlayAreaAlias centre is wanted to be moved to
the teleport point.
This is now possible by optionally setting the Offset parameter
on the TransformPropertyApplier inside the HeightAdjustTeleporter
GameObject.
The parameter fields have also changed to be more generic.
PlayAreaAlias becomes Target
HeadsetAlias becomes Offset
And a new bool, of `OnlyOffsetFloorSnap` allows for the offset
on teleport to be optional. If the setting is true then the Offset
is only applied when doing floor snapping, which has to always be
applied and cannot be optional.
> feat(Locomotion): allow teleport offset to be optional - resolves #207

- Prefabs/CameraRig/PlayAreaRepresentation/PlayAreaRepresentation.prefab
- Prefabs/CameraRig/SimulatedCameraRig/SharedResources/Scripts/ActiveObjectInternalSetup.cs
- Prefabs/CameraRig/SimulatedCameraRig/[SimulatedCameraRig].prefab
- Prefabs/Interactions/Interactables/Interactable.Climbable.prefab
- Prefabs/Locomotion/Movement/AxesToVector3/AxesToVector3.prefab
- Prefabs/Locomotion/Movement/AxesToVector3/SharedResources/Scripts/AxesToVector3InternalSetup.cs
- Prefabs/Locomotion/Movement/Climb/Climb.prefab
- Prefabs/Locomotion/Movement/Climb/SharedResources/Scripts/ClimbFacade.cs
- Scripts/Data/Type/Transformation/CollectionAggregator.cs
- Scripts/Data/Type/Transformation/FloatMultiplier.cs
- Scripts/Data/Type/Transformation/Vector2Multiplier.cs
- Scripts/Data/Type/Transformation/Vector3Multiplier.cs
- Tests/Editor/Data/Type/Transformation/FloatAdderTest.cs
- Tests/Editor/Data/Type/Transformation/FloatMultiplierTest.cs
- Tests/Editor/Data/Type/Transformation/Vector2MultiplierTest.cs
- Tests/Editor/Data/Type/Transformation/Vector3MultiplierTest.cs
- Tests/Editor/Data/Type/Transformation/Vector3SubtractorTest.cs
The various Multipler transformations now extend CollectionAggregator
as multiplication is an aggregate function across a collection of
values.
Now it's possible to multiple a range of float/vector2/vector3 values
as they extend the base aggregator.
The prefabs have been updated and the general rule is the dynamic
multiplication value is always index 0 and the multipler is always
set to index 1. This way the event updating the dynamic value never
has to bother setting the current index in the collection.
> refactor(Transformation): convert multipliers to be aggregators - fixes #217

- Scripts/Tracking/Collision/Active/ActiveCollisionsContainer.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionsContainerTest.cs
The ActiveCollisionContainer can now have a rule applied to it to
determine which collisions can be added to the collection.
This is useful for separating out collisions from a CollisionTracker
for purposes such as near touching objects where the engulfing
collider can prevent the inner collider from being notified of
touch events.
> feat(Collision): add active collision validity rule - fixes #194

- Scripts/Haptics/HapticProcessor.cs
There was an issue where the `IsActive()` check on the HapticProcessor
would always report false because the ActiveProcess was never set until
the `Begin()` method was called, but the `IsActive()` check was being
done before the `Begin()` method was executed.
This resulted in the HapticProcessor never being able to actually
process any valid HapticProcesses.
The fix is to just set the ActiveProcess in `OnEnable` so at least one
is set when it is enabled.
> fix(Haptics): ensure ActiveProcess is set when processor enabled

- Prefabs/Locomotion/Movement/MovementAmplifier.meta
- Prefabs/Locomotion/Movement/MovementAmplifier/MovementAmplifier.prefab
- Prefabs/Locomotion/Movement/MovementAmplifier/MovementAmplifier.prefab.meta
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources.meta
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources/Scripts.meta
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources/Scripts/MovementAmplifierFacade.cs
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources/Scripts/MovementAmplifierFacade.cs.meta
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources/Scripts/MovementAmplifierInternalSetup.cs
- Prefabs/Locomotion/Movement/MovementAmplifier/SharedResources/Scripts/MovementAmplifierInternalSetup.cs.meta
- Scripts/Data/Type/Transformation/Vector3MagnitudeSetter.cs
- Scripts/Data/Type/Transformation/Vector3MagnitudeSetter.cs.meta
- Tests/Editor/Data/Type/Transformation/Vector3MagnitudeSetterTest.cs
- Tests/Editor/Data/Type/Transformation/Vector3MagnitudeSetterTest.cs.meta
The movement of a game object can be amplified by applying the same
movement to another object. The feature comes with a multiplier
allows setting the amplification amount as well as a threshold that
allows ignoring movement in a radius. In VR experiences this feature
can be used to amplify movement of the headset to allow traveling
larger distances than the physical play area allows. The threshold
radius prevents amplifying movement while the user is not moving and
instead just crouches.
> feat(MovementAmplifier): amplify movement of a game object - resolves #49

- Prefabs/Helpers/ObjectFollower/ObjectFollower.prefab
The ObjectFollower prefab now has the position, rotation, scale follow
modifiers as child GameObjects as this makes it easier to disable
certain follow actions by simply disabling the GameObject.
> refactor(Helpers): place follow modifiers in child game objects

- Scripts/Data/Type/Transformation/Vector3MagnitudeSetter.cs
The `Vector3MagnitudeSetter` class offers methods that were not yet
marked as `virtual` to allow subclasses to override them.
> fix(Transformation): virtual methods for Vector3MagnitudeSetter

- Scripts/Tracking/Query.meta
- Scripts/Tracking/Query/ObscuranceQuery.cs
- Scripts/Tracking/Query/ObscuranceQuery.cs.meta
A new component has been added that allows querying whether any
collider obscures a line between two GameObjects. An example use
case is disabling the teleportation functionality on a VR controller
while it's obscured from the headset to prevent users from moving
the controller through virtual walls and ultimately teleport through
it.
> feat(Query): add obscurance query - resolves #51

- Prefabs/CameraRig/PlayAreaRepresentation/PlayAreaRepresentation.prefab
- Prefabs/CameraRig/SimulatedCameraRig/SimulatedCameraRig.prefab
- Prefabs/Locomotion/Movement/Climb/Climb.prefab
- Prefabs/Locomotion/Movement/MovementAmplifier/MovementAmplifier.prefab
- Scripts/Data/Operation/TransformPropertyMutator.cs
- Tests/Editor/Data/Operation/TransformEulerRotationMutatorTest.cs
- Tests/Editor/Data/Operation/TransformPositionMutatorTest.cs
The TransformPropertyMutator had a Vector3State called `lockAxis` which
had the negative connotation that any checked box would not perform the
mutation on the axis. Other uses are positive connotations i.e. the
checked axis box means an operation **would** be performed on that
axis.
The `lockAxis` field has been changed for a `mutateOnAxis` field which
uses the positive connotation of any checked box will be mutated.
The prefabs that used the TransformPropertyMutators have also been
updated so the logic is flipped.
> fix(Operation): replace negative with positive connotation of axis lock - fixes #238

- Scripts/Action/Action.cs
- Tests/Editor/Action/BooleanActionTest.cs
- Tests/Editor/Action/FloatActionTest.cs
The Action now sets the Value to the defaultValue on component awake
otherwise the current value is incorrect when the first ProcessValue
is called on the action.
Tests have been added to show the issue and prove the fix works.
> fix(Action): ensure Value matches default value on Awake

- Runtime/Tracking/Follow/Modifier/Property/PropertyModifier.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocityTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Position/TransformPositionTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocityTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformRotationTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Scale/TransformScaleTest.cs
According to the code conventions properties should use PascalCase,
not camelCase.
> chore(Tracking): fix case of property name

- Runtime/Tracking/Modification/TransformPropertyApplier.cs
Methods that take arguments need their parameters documented by
using XML documentation comments. This fix ensures the whole
codebase does so.
> chore(Tracking): fix missing XML parameter documentation

- Runtime/Data/Type/Vector3State.cs
- Tests/Editor/Data/Type/Vector3StateTest.cs
The Vector3State has some additional shorthand options for setting
states that represent the x, y, z coordinate.
> feat(Data): add shorthand Vector3State options

- Runtime/Data/Type/FloatRange.cs
- Tests/Editor/Data/Type/FloatRangeTest.cs
The default constructor of the FloatRange creates a FloatRange with a
float minimum and float maximum value, but on occasion it is useful to
set the default to zero (0f, 0f) without having to manually create the
constructor so a shorthand static FloatRange.Zero has been added.
> feat(Data): add zero value shortcut to FloatRange

- Runtime/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotation.cs
- Runtime/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotation.cs.meta
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotationTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotationTest.cs.meta
The TransformPositionDifferenceRotation rotates the target by following
the position change of the source object allowing a pseudo rotation of
an object to mimic spinning an object around an axis based on the
position of the controlling source objects.
> feat(Follow): rotate target by following position change of source

- Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs
XML documentation comments that reference an identifier were updated
to ensure they reference identifiers by their correct name.
> chore(structure): fix invalid XML documentation comments

- Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
`Vector3RestrictorTest` was a `MonoBehaviour` which is wrong and
results in warnings being logged by Unity when running the test as
creation of behaviours isn't possible in the Unity test runner this
way. The fix is to make `Vector3RestrictorTest` a regular C# class.
> chore(tests): fix warning log for Vector3RestrictorTest

- Runtime/Data/Operation/GameObjectCloner.cs
- Runtime/Data/Operation/GameObjectCloner.cs.meta
- Tests/Editor/Data/Operation/GameObjectClonerTest.cs
- Tests/Editor/Data/Operation/GameObjectClonerTest.cs.meta
- Tests/Editor/Tracking/Follow/ObjectDistanceComparatorEventDataExtractorTest.cs
- Tests/Utility/Mock/UnityEventListenerMock.cs
- Tests/Utility/Mock/UnityEventValueListenerMock.cs
- Tests/Utility/Mock/UnityEventValueListenerMock.cs.meta
`GameObjectCloner` allows duplicating a `GameObject` by cloning it.
The component allows to optionally specify which `GameObject` to
parent the cloned object to and raises an event with the cloned
object.
> feat(Data): add GameObject cloner

- Runtime/Tracking/Collision/Active/Operation/NotifierTargetExtractor.cs
- Runtime/Tracking/Collision/Active/Operation/NotifierTargetExtractor.cs.meta
- Tests/Editor/Tracking/Collision/Active/Operation/NotifierTargetExtractorTest.cs
- Tests/Editor/Tracking/Collision/Active/Operation/NotifierTargetExtractorTest.cs.meta
`NotifierTargetExtractor` allows extracting the collision **target**
out of a `CollisionNotifier`'s event data. This new component can
prevent writing tiny components to deal with the other end of a
collision happening on a known collider that is observed via
`CollisionNotifier`.
> feat(Tracking): add extractor for collision target

- Runtime/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocity.cs
- Runtime/Tracking/Modification/DirectionModifier.cs
floats can't be compared via `==`, thus this fix ensures they are
done using the appropriate method.
> fix(Tracking): float comparisons

- Tests/Utility/TimeSettingOverride.cs
`AddComponentMenu` is only usable on classes that inherit from
`MonoBehaviour`. This fix removes the attribute as well as the
default constructor as it's unused.
> chore(Tests): fix wrong attribute usage

- Runtime/Data/Type/FloatRange.cs
- Runtime/Data/Type/Transformation/Vector3Restrictor.cs
- Tests/Editor/Data/Type/FloatRangeTest.cs
- Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
There were times where using the FloatRange.Zero helper would return
the same instance across different instantiations which won't happen
if the FloatRange is a struct instead of a class.
It makes more sense for the FloatRange to be a struct as other custom
Types included are structs unless a class is required.
Due to the FloatRange becoming a struct means a default constructor
is no longer provided which set the value to float.MinValue and
float.MaxValue so a new static helper called FloatRange.MinMax has been
added that returns the same data. Whereas a `new FloatRange()` now will
return the default values for min, max (which is 0f, 0f) so there is no
need to use the `FloatRange.Zero` helper now so that has been removed.
> fix(Data): convert FloatRange to struct to prevent instancing issues - fixes #291

- Runtime/Rule/AllRule.cs
- Runtime/Rule/AnyLayerRule.cs
- Runtime/Rule/AnyRule.cs
- Runtime/Rule/GameObjectRule.cs
- Runtime/Rule/ListContainsRule.cs
- Runtime/Rule/NegationRule.cs
- Tests/Editor/Rule/ActiveInHierarchyRuleTest.cs
- Tests/Editor/Rule/AllRuleTest.cs
- Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
- Tests/Editor/Rule/AnyLayerRuleTest.cs
- Tests/Editor/Rule/AnyRuleTest.cs
- Tests/Editor/Rule/ListContainsRuleTest.cs
- Tests/Editor/Rule/NegationRuleTest.cs
All rules now implement the `[RequiresBehaviourState]` attribute so
if the component or GameObject that the rule is on is disabled then
the rule will be ignored.
> feat(Rule): allow rules to be ignored if the component is disabled

- Runtime/Pointer/ObjectPointer.cs
- Runtime/Visual/CameraColorOverlay.cs
- Runtime/Visual/PointsRenderer.cs
- Tests/Editor/Visual/CameraColorOverlayTest.cs
- Tests/Editor/Visual/PointsRendererTest.cs
All usages of a field have now been updated to use a serialized
property to allow setting of data via UnityEvents.
New helper methods have been implemented to allow changes to
properties via code or the inspector to react to the changes and
update any relevant components as required.
The CameraColorOverlay component now also uses a working material to
apply the color overlay to instead of working directly on the injected
material. This means the injected material is used as a blueprint but
is never changed at runtime.
This new working material is automatically updated anytime the
OverlayMaterial property is changed.
> feat(Visual): update all fields to serialized properties

- Runtime/Utility/CountdownTimer.cs
- Runtime/Utility/InterfaceContainer.cs
- Tests/Editor/Utility/CountdownTimerTest.cs
- Tests/Editor/Utility/CountdownTimerTest.cs.meta
All usages of fields have now been switched to properties that
are serialized with Malimbe to create an appropriate backing field
to display in the Unity Inspector.
New helper methods have been implemented to allow changes to
properties via code or the inspector to react to the changes and
update any relevant components as required.
Also, now the tests run in play mode, the CountdownTimer can be
tested so a new test has been added to unit test the functions
of the CountdownTimer component.
> feat(Utility): update all fields to be serialized properties

- Runtime/Data/Collection/ObservableList.cs
- Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
The ObservableList component now has additional functionality like
being able to check if the collection contains a given item and
set an element value at a specific index.
The fields have now been converted to properties and a new CurrentIndex
field has been added that allows methods that require an index to
still function if called via the limitations of a UnityEvent (which
only allows one parameter type).
> feat(Collection): add extra functionality to ObservableList

- Runtime/Utility/InterfaceContainer.cs
The InterfaceContainer was updated to provide a different logic path
when it was deserialized to ensure the `(Field != null)` check wasn't
performed in the `OnAfterDeserialize` call. However, the `Field`
property being set after deserialization is also enough to cause
an error and instead the backing field is what needs setting to
remove the error.
> fix(Utility): set field instead of property after deserialization

- Runtime/Haptics/AudioClipHapticPulser.cs
- Runtime/Haptics/Collection.meta
- Runtime/Haptics/Collection/HapticProcessObservableList.cs
- Runtime/Haptics/Collection/HapticProcessObservableList.cs.meta
- Runtime/Haptics/HapticProcessor.cs
- Runtime/Haptics/HapticPulser.cs
- Runtime/Haptics/TimedHapticProcess.cs
- Runtime/Haptics/XRNodeHapticPulser.cs
All usages of fields have now been switched to properties that are
serialized with Malimbe to create an appropriate backing field to
display in the Unity Inspector.
All uses of List collections have also been replaced with concrete
versions of the ObservableList, which makes it possible to track
changes occurring to the lists at runtime and provides a single
component that allows mutating the list via UnityEvents.
> feat(Haptics):  update fields to properties and lists to observable

- Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
- Tests/Editor/Data/Collection/GameObjectObservableSetTest.cs
- Tests/Editor/Data/Operation/GameObjectClonerTest.cs
- Tests/Editor/Tracking/Follow/Modifier/FollowModifierTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Scale/TransformScaleTest.cs
- Tests/Editor/Tracking/Modification/GameObjectStateMirrorTest.cs
- Tests/Editor/Tracking/Modification/PinchScalerTest.cs
When GameObjects are created in tests, they should be immediately
destroyed at the end of the test to prevent creating a dirty scene
for the next test.
This fix ensures no created GameObjects have been left around at
the end of a test.
> fix(tests): ensure created objects are destroyed within the test

- Runtime/Cast/FixedLineCast.cs
- Runtime/Cast/ParabolicLineCast.cs
- Runtime/Cast/PhysicsCast.cs
- Runtime/Cast/PointsCast.cs
- Runtime/Cast/StraightLineCast.cs
- Runtime/Pointer/ObjectPointer.cs
- Runtime/Tracking/Modification/PointNormalRotator.cs
- Tests/Editor/Cast/FixedLineCastTest.cs
- Tests/Editor/Cast/ParabolicLineCastTest.cs
- Tests/Editor/Cast/StraightLineCastTest.cs
- Tests/Editor/Pointer/ObjectPointerTest.cs
- Tests/Editor/Tracking/Modification/PointNormalRotatorTest.cs
All usages of fields have now been switched to properties that are
serialized with Malimbe to create an appropriate backing field to
display in the Unity Inspector.
All uses of List collections have also been replaced with concrete
versions of the ObservableList, which makes it possible to track
changes occurring to the lists at runtime and provides a single
component that allows mutating the list via UnityEvents.
> feat(Cast): update fields to properties and lists to observable

- Runtime/Association/Collection.meta
- Runtime/Association/Collection/GameObjectsAssociationObservableList.cs
- Runtime/Association/Collection/GameObjectsAssociationObservableList.cs.meta
- Runtime/Association/GameObjectsAssociation.cs
- Runtime/Association/GameObjectsAssociationActivator.cs
- Runtime/Association/LoadedXrDeviceAssociation.cs
- Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
All usages of fields have now been switched to properties that are
serialized with Malimbe to create an appropriate backing field to
display in the Unity Inspector.
All uses of List collections have also been replaced with concrete
versions of the ObservableList, which makes it possible to track
changes occurring to the lists at runtime and provides a single
component that allows mutating the list via UnityEvents.
> feat(Association): update fields to properties and lists to observable

- Runtime/Pointer/ObjectPointer.cs
- Runtime/Pointer/PointerElement.cs
- Runtime/Pointer/PointerElement.cs.meta
- Tests/Editor/Pointer/ObjectPointerTest.cs
All usages of fields have now been switched to properties that are
serialized with Malimbe to create an appropriate backing field to
display in the Unity Inspector.
All uses of List collections have also been replaced with concrete
versions of the ObservableList, which makes it possible to track
changes occurring to the lists at runtime and provides a single
component that allows mutating the list via UnityEvents.
The ObjectPointer has also been split up so the Pointer Element
is now its own MonoBehaviour component to make it easier to
change pointer elements in the inspector.
> feat(Pointer): update fields to properties and lists to observable

- Runtime/Tracking/Collision/CollisionIgnorer.cs
- Runtime/Tracking/Collision/CollisionIgnorer.cs.meta
- Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
- Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs.meta
The CollisionIgnorer component takes a list of source GameObjects
and a list of target GameObjects and ignores all source colliders
from colliding with all target colliders.
The CollisionIgnorer ignores the collisions on enable and restores
the collisions on disable.
There is no direct access to the lists via code and new items must
be added via methods and removed via methods.
Adding new items to the list at runtime via the inspector yields no
changes to the collision detection.
> feat(Collision): add ability to ignore collisions between GameObjects

- Editor/Data/Collection/ObservableListEditor.cs
- Runtime/Action/ActionRegistrar.cs
- Runtime/Action/AllAction.cs
- Runtime/Action/AnyAction.cs
- Runtime/Data/Collection/ObservableCounter.cs
- Runtime/Data/Collection/ObservableList.cs
- Runtime/Tracking/Collision/CollisionIgnorer.cs
- Tests/Editor/Data/Collection/GameObjectObservableCounterTest.cs
- Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
The events in the ObservableList have been renamed to more appropriate
event names to make it clearer and more precise of their use.
> feat(Collection): rename events in ObservableList

- Editor/Data/Collection/ObservableListEditor.cs
- Runtime/Data/Collection/ObservableList.cs
When changing the size of an ObservableList via the inspector the
custom inspector would not call the events while the list is in the
expected state. The fix is to revert changes Unity already did
through serialization, then call the same API a code change would
call. This ensures the events are raised while the list is in the
same state it would be if the change is done via code or a
UnityEvent listener.
> fix(Data): ensure correct list state when emitting inspector events - fixes #333

- Editor/Data/Attribute/RestrictedAttributeDrawer.cs
- Runtime/Data/Attribute/RestrictedAttribute.cs
The Restricted attribute now has a couple of additional options for
defining a read-only field. It now can be:
* ReadOnlyAlways: Always readonly
* ReadOnlyAtRunTime: Readonly when the app is playing
* ReadOnlyAtRunTimeAndEnabled: Readonly on playing and script enabled
* ReadOnlyAtRunTimeAndDisabled: Readonly on playing and script disabled
This offers a complete solution to times where readonly may be
required. Also, the `Muted` option has been moved to the top to make
things look neater.
> feat(Attribute): add additional readonly options to Restricted

- Runtime/Action/Collection/ActionRegistrarSourceObservableList.cs
- Runtime/Haptics/HapticProcessor.cs
- Runtime/Process/Component/GameObjectSourceTargetProcessor.cs
- Runtime/Process/Moment/MomentProcessor.cs
- Runtime/Rule/AllRule.cs
- Runtime/Rule/AnyComponentTypeRule.cs
- Runtime/Rule/AnyRule.cs
- Runtime/Rule/AnyTagRule.cs
- Runtime/Rule/RulesMatcher.cs
- Runtime/Tracking/Follow/ObjectFollower.cs
- Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
- Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
- Runtime/Tracking/Velocity/VelocityTrackerProcessor.cs
- Tests/Editor/Action/Collection/ActionRegistrarSourceObservableListTest.cs
- Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
- Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
All components have been updated to use the non-subscribable variant
of the list from ObservableList in case they don't actually handle
changes in a reactive way and instead poll the state of the list.
The tests have also been changed to use the non-subscribable variant
except for the tests that test the reactive components.
> chore(general): use ObservableList.NonSubscribableElements instead - resolves #326

- Runtime/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocity.cs
`Time.deltaTime` is the preferred way to get the delta time because
it automatically returns the right time depending on whether the
code is running as part of the fixed update loop or the regular
update loop.
> fix(Tracking): use correct delta time independent of loop type

- Tests/Editor/Rule/AnyComponentTypeRuleTest.cs
An old to-do comment has been resolved (indirectly) in the past and
thus the comment can be removed.
> chore(Rule): remove TODO comment

- Runtime/Tracking/Query/ObscuranceQuery.cs
- Tests/Editor/Tracking/Query/ObscuranceQueryTest.cs
ObscuranceQuery currently requires a Collider as the target, however
this is limiting when using objects that contain compound colliders.
This change allows providing a GameObject as the target instead and
use that for the collision check. Additionally an exception is
thrown in case the target doesn't have any Rigidbody, nor Collider
on it to prevent users of the component from silently never getting
any result. More information can be found in [Unity's
documentation](https://docs.unity3d.com/Manual/CollidersOverview.html).
> feat(Tracking): allow GameObject as Target in ObscuranceQuery - resolves #264

- Tests/Editor/Association/GameObjectsAssociationActivatorTest.cs
One of the tests for `GameObjectsAssociationActivator` tests whether
an expected warning log message is actually logged. As this warning
log can be seen as a (partial) failure in the test by users running
the tests, the test has been adjusted to log additional information
before and after the expected warning log. These messages explain
that the warning is indeed expected and intended.
> chore(Association): explain why the test results in a warning log

- Runtime/Tracking/CameraRig/Collection.meta
- Runtime/Tracking/CameraRig/Collection/LinkedAliasAssociationCollectionObservableList.cs
- Runtime/Tracking/CameraRig/Collection/LinkedAliasAssociationCollectionObservableList.cs.meta
The LinkedAliasAssociationCollection now has an ObservableList type for
holding a collection of linked alias associations.
> feat(CameraRig): add observable list for linked alias association

- Runtime/Tracking/Modification/GameObjectStateSwitcher.cs
- Tests/Editor/Tracking/Modification/GameObjectStateSwitcherTest.cs
The GameObjectStateSwitcher does not need to hold an internal
CurrentIndex property as there is a CurrentIndex property on the
ObservableList and as the GameObjectStateSwitcher uses a
GameObjectObservableList to traverse the collection, it's more
appropriate to use the CurrentIndex on that ObservableList.
> feat(Modification): remove local CurrentIndex property

- Runtime/Tracking/Modification/ComponentEnabledStateModifier.cs
- Tests/Editor/Tracking/Modification/ComponentEnabledStateModifierTest.cs
The ComponentEnabledStateModifier originally used a
SerializedTypeBehaviourObservableList but this only allows picking
classes that extend Behaviour and Renderers in Unity do not extend
Behaviour. Instead, a SerializedTypeComponentObservableList is now used
which allows picking any Behaviours and any Renderers.
The component already ensures it does nothing if a component with no
enabled type is picked.
> fix(Modification): switch from behaviour to component observable list

- Runtime/Data/Collection/ObservableList.cs
- Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
The ObservableList now has a new method that allows setting an element
in the collection or adding it to the collection if the collection is
empty.
This is a somewhat obscure requirement and it in fact does two
operations but is required due to the limitations of UnityEvents where
only rudimentary logic is possible.
The Remove method has also been updated so it returns a bool and a
DoRemove method has been added that returns nothing so it can still
be used in UnityEvents.
> feat(Collection): add method to set element or add if empty to list

- Runtime/Tracking/Collision/CollisionIgnorer.cs
The CollisionIgnorer didn't specify the access modifier for the two
Collider lists being used internally which would mean they were set
to the default of `private` which prevents using them in any classes
that extend it.
They have now been set to `protected` so extending the class and using
these fields is possible.
> fix(Collision): provide access modifier on internal lists

- Runtime/Tracking/Query/ObscuranceQuery.cs
- Tests/Editor/Tracking/Query/ObscuranceQueryTest.cs
The ObscuranceQuery was not correctly checking to see if a Target
without a rigidbody but with a compound collider was invalid.
The tests have been updated to show the issue and to prove the fix
works.
> fix(Query): ensure obscurance target has a valid compound collider

- Runtime/Data/Collection/ObservableList.cs
- Tests/Editor/Data/Collection/GameObjectObservableListTest.cs
- Tests/Editor/Process/Component/GameObjectSourceTargetProcessorTest.cs
- Tests/Editor/Tracking/Follow/ObjectFollowerTest.cs
The ObservableList Clear method now has a default value for the Clear
parameter set to false to just reduce the amount of times Clear(false)
is required, when simply Clear() can be used, which is the standard
operation.
> feat(Collection): provide default value for Clear parameter

- Runtime/Extension/BehaviourExtensions.cs
- Runtime/Extension/BehaviourExtensions.cs.meta
- Tests/Editor/Extension/BehaviourExtensionsTest.cs
- Tests/Editor/Extension/BehaviourExtensionsTest.cs.meta
The BehaviourExtensions provide a mechanism to queue up a behaviour
action on a component to run when the component becomes enabled. This
makes it possible to run methods on disabled components by waiting
for them to become enabled and then running the appropriate method.
This is very useful for calling ObservableList methods such as Add
in the OnEnable method of other components in case there is a race
condition of which component becomes enabled first.
> feat(Extension): ability to queue a behaviour action to run on enable

- Runtime/Tracking/Collision/CollisionIgnorer.cs
- Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
The CollisionIgnorer was not resuming collisions when the component
was disabled due to a short circuit check failing because the logic
was there to prevent resuming collisions when removing an item from
the list.
The fix ensures that check is only done when the toggle is done
via the list mutation and not when disabled.
An additional parameter has also been added to optionally toggle
collisions on inactive colliders if required.
> fix(Collision): ensure ignored collisions are resumed on disable

- Runtime/Cast/FixedLineCast.cs
- Runtime/Cast/ParabolicLineCast.cs
- Runtime/Cast/PointsCast.cs
- Runtime/Cast/StraightLineCast.cs
- Runtime/Pointer/ObjectPointer.cs
- Runtime/Tracking/Modification/PointNormalRotator.cs
- Tests/Editor/Cast/ParabolicLineCastTest.cs
- Tests/Editor/Cast/StraightLineCastTest.cs
- Tests/Editor/Pointer/ObjectPointerTest.cs
- Tests/Editor/Tracking/Modification/PointNormalRotatorTest.cs
The PointsCast now allows target collisions that do not pass the
validity rules to emit their data instead of null but along with a
new IsValid flag so it's possible to know whether the collision is
with a valid target.
This data is now used in the ObjectPointer so it's possible with the
ObjectPointer to know when you're hovering over an invalid target
but selecting an InvalidTarget still emits `Selected(null)` as an
invalid target is considered the same as no target at all.
> feat(Cast): provide validity data along with hit data - fixes #104

- Runtime/Action/Action.cs
There was an issue when increasing or decreasing the Sources List size
in the inspector as this would trigger the OnChange handlers for the
Sources and attempt to subscribe/unsubscribe on the Action. However, by
default Unity will create a null action when increasing the size of an
empty List which would then attempt to register a null Action and
therefore it would throw an error.
The larger problem became when then trying to remove the null actions
in the inspector as because errors were being thrown meant the
inspector wouldn't update and would stay in a broken state.
This fix ensures the passed action is null checked. This does mean that
null actions will silently fail and not provide any useful feedback if
attempted, but it's required to work around the limitations and issues
in the …
> fix(Action): prevent null actions being subscribed to/from

- Runtime/Haptics/TimedHapticProcess.cs
- Tests/Editor/Data/Collection/GameObjectRelationsTest.cs
- Tests/Editor/Tracking/Velocity/ComponentTrackerProxyTest.cs
Some `using` statements were unnecessary and have been removed.
> chore(general): remove unused namespace imports

- Tests/Editor/Tracking/Velocity/ComponentTrackerProxyTest.cs
A test was incorrectly calling old API that was since replaced with
Malimbe. This still compiled so far in Unity because Malimbe injects
the called method before the test assembly is created, thus the
method is found and can be called without issues. The method is
primarily injected to help with UnityEvent usage of the logic the
method implements, thus this change can replace the call to the
injected method by the API that is available to code at all times:
The property setter.
> chore(Tracking): fix unresolved method error in a test

- .github/ISSUE_TEMPLATE.md
- README.md
There were reports that Zinnia was not working correctly on
earlier versions of Unity 2018.3 and due to numerous XR bug fixes
in Unity 2018.3 it's best to recommend 2018.3.10f1 as it is the
least buggy in XR space.
> docs(README.md): update minimum Unity version number

- Runtime/Tracking/Modification/PinchScaler.cs
The PinchScaler was not reporting the correct distances between
pinch points if either the primary or secondary point changed
(or was cleared) as the code would only reset the previous
distance back to null if the component was disabled. It should
also reset the previous distance check to null if either the
primary or secondary points change so the previous distance in
the process calculation is recreated to have the correct initial
distance delta.
> fix(Tracking): reset distance check when pinch points change

- Runtime/Pointer/ObjectPointer.cs
There are occasions where the existing pointer data needs reprocessing
but the component requiring the rehandling does not contain pointer
data.
One case is when the PointerElement visibility changes, it requires
the existing pointer data to be reprocessed again.
This method provides a quick and simple way to reprocess the existing
pointer data.
> feat(Pointer): rehandle existing pointer data

- README.md
The project backlog has been moved to GitHub projects as Waffle.io
is being shutdown.
The License badge has also been added to bring it inline with the
other repos.
> docs(README.md): update backlog link to GitHub projects

- Tests/Editor/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocityTest.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocityTest.cs
Gravity was being applied to the rigidbodies in the tracking
modifier tests causing them to sometimes be falling at the point
of the initial position/rotation assertion, which should have been
zero.
Gravity is now turned off on the rigidbody, which will prevent it
from falling and therefore the tests will pass.
> fix(Tracking): remove gravity from rigidbody tests

- Runtime/Rule/AnyLayerRule.cs
- Tests/Editor/Rule/AnyLayerRuleTest.cs
The AnyLayerRule was not correctly matching against the specified
LayerMask and the tests were also incorrect and therefore not
highlighting the issue.
In the tests where it would set up the LayerMask by doing
`subject.LayerMask = LayerMask.NameToLayer("UI")` this would not
actually set the LayerMask property to `UI` instead it would set
it to `Default` and `Ignore Raycast`. The correct way to set the
LayerMask property is to use `LayerMask.GetMask("UI")` which then
will select the correct property and highlight the issue in the
AnyLayerRule.
The AnyLayerRule is then fixed by checking the LayerMask property
is equal to the existing LayerMask with the target layer pushed
on to it.
This makes all of the tests pass and also works by testing with
scene objects.
> fix(Rule): ensure layer rule matches correctly against layer mask

- Runtime/Tracking/Collision/CollisionNotifier.cs
- Tests/Editor/Tracking/Collision/CollisionNotifierTest.cs
- Tests/Editor/Tracking/Collision/CollisionNotifierTest.cs.meta
- Tests/Editor/Tracking/Collision/CollisionTrackerTest.cs
- Tests/Editor/Tracking/Collision/CollisionTrackerTest.cs.meta
The CollisionNotifier.EventData equality check was only checking to
see if one side of the collision matched to determine if the collision
data was equal.
This is incorrect as the following should be true:
```
A collides with B == A collides with B
A collides with B != A collides with C
A collides with B != C collides with B
```
However, previously this was actually the case
`A collides with B == C collides with B`
Because the second object of the collision was only being checked for
equality therefore if two different objects (A, C) collided with the
same target (B) then the EventData would be considered equal whereas
the collision is not equal.
The fix is to ensure if there is a forwarding source of the collision
then that should also be used in the equality check.
Additional tests have …
> fix(Collision): utilize both colliding objects in equality check

- Runtime/Tracking/Collision/Active/ActiveCollisionsContainer.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionsContainerTest.cs
The ActiveCollisionsContainer could have duplicate collisions added
to the container which is incorrect because only 1 collision is really
valid and required. It would also create a leak if the collision was
never removed but due to a Unity bug if the colliding object was
disabled then the collision would not be removed but would be readded
again if the colliding object was enabled again.
> fix(Tracking): prevent duplicate active collisions in collection

- Runtime/Tracking/Collision/CollisionNotifier.cs
- Runtime/Tracking/Collision/CollisionTracker.cs
- Tests/Editor/Tracking/Collision/CollisionNotifierTest.cs
- Tests/Editor/Tracking/Collision/CollisionTrackerTest.cs
The CollisionTracker now has an enum flag to determine which collision
states to process. Any ignored collision state simply will return early
in the OnCollision/Trigger method related to the state.
This gives the option of forcing any CollisionTracker to never process
a state if it's never required because at the moment it will always
at least run through the process of looking for CollisionNotifiers.
> feat(Collision): ability to ignore tracked collision states

- Runtime/Tracking/Collision/CollisionTracker.cs
- Tests/Editor/Tracking/Collision/CollisionTrackerTest.cs
There is an issue in Unity where when two objects are colliding will
create a collision started event, but whilst the objects are
intersecting, if one of the objects is disabled then Unity does not
consider this to stop the collision between the two objects so no
OnCollisionExit or OnTriggerExit occurs. However, if the disabled
object is re-enabled and is still in the same intersecting position
then Unity will consider this a new Enter event.
This causes a problem for the CollisionTracker as it means the state
of the tracker can become out of sync. If a collision starts twice
but no stop was called between, then the tracked collision state is
not valid. This would then have knock on effects in usages such as
the ActiveCollisionsContainer where a started collision is treated
as an active …
> fix(Collision): stop collisions when either side is disabled - fixes ExtendRealityLtd/VRTK#2005

- Runtime/Tracking/Collision/CollisionNotifier.cs
The CollisionNotifier.EventData was performing the equality check on
the ForwardSource of the collision and the containing Transform of
the collider being intersected. This actually can report invalid
equality data as two compound colliders being touched by the same
ForwardSource would report as being the same Collision Data which
they're actually not.
The fix is to just do the equality check directly on the Collider and
the ForwardSource.
The HashCode of the EventData should also be a combination of the
two equality checked objects to ensure its uniqueness.
> fix(Collision): perform equality check on collider and forward source

- Runtime/Tracking/Collision/CollisionNotifier.cs
- Runtime/Tracking/Collision/CollisionTracker.cs
The CollisionNotifier reuses a collection for the found collision
notifiers to remove any garabge, however, this caused an issue if the
OnCollisionXXX methods were called again by anything during the process
as any additional call would attempt to re-load in any found collision
notifiers thus mutating the collection and causing the initial
`foreach` to fail due to the collection being changed.
As there is no need to allow the reprocessing of the notifier
collection as all notifiers should get processed on the first pass,
then the fix is to simply exit the methods early if they are called
again from the within the `foreach` instruction.
The cached collection has now been split up into 3 distinct collections
for each of the collision types ecause there could be occasions where
different …
> fix(Collision): prevent notifier collection enumeration multiple times

- Editor/Data/Type/CollapsibleUnityEventDrawer.cs
- Editor/Data/Type/CollapsibleUnityEventDrawer.cs.meta
A new custom PropertyDrawer that overrides the UnityEventDrawer has
been added to allow the ability to wrap a UnityEvent inspector control
in a foldout so the UnityEvent control can be collapsed.
Reflection is required to override the default UnityEventDrawer
inspector drawing ue to the way Unity creates the UnityEventDrawer
internally.
> feat(Type): add collapsible UnityEvent drawer

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
The formatting of the Markdown has been fixed to remove any
unnecessary leading spaces.
> docs(structure): fix markdown formatting

- Editor/Data/Type/DefaultObservableListDrawer.cs
There is an issue with manually building the list out of the
instantiated list object data as it will never pass through Unity's
serializer and therefore any changes will not be serialized to disk
meaning the control doesn't actually persist changes when the
scene is saved.
This fix removes all of the custom code and simply gets a
SerializedObject of the referenced property and uses the Unity
built in PropertyField to render the field which will ensure the
property changes are serialized to disk.
This does have the drawback that the rendered property drawer does
not utilize the custom ObservableListEditor which handles manually
firing the Observable List events when changes occur. This means
any changes to the Elements list in a reference property (i.e. using
this custom property drawer) …
> fix(Data): utilize SerializedObject data to draw list elements

- Tests/Editor/Data/Operation/Extraction/SurfaceDataCollisionPointExtractorTest.cs
The SurfaceDataCollisionPointExtractor test was failing because it used
a RayCast to fill the HitData properties to allow the process to
continue, however an Editor test won't actually do the RayCast in newer
versions of Unity unless the physics is manually simulated or
[UnityTest] is used. For the sake of what this test is actually doing,
it's easier to just manually process the physics simulation.
> fix(Extraction): simulate raycast for surface data ray

- Tests/Editor/Pointer/ObjectPointerTest.cs
The hover target should be the transform in collision data
Not the hover target transform (which is the object pointer)
#415
> fix(Pointers): check hover target collision data in select test

- Runtime/Data/Type/Transformation/FloatRangeValueRemapper.cs
- Runtime/Data/Type/Transformation/FloatRangeValueRemapper.cs.meta
- Tests/Editor/Data/Type/Transformation/FloatRangeValueRemapperTest.cs
- Tests/Editor/Data/Type/Transformation/FloatRangeValueRemapperTest.cs.meta
The FloatRemapper component allows a float value to be remapped from
a range to another range, with an option to map the output linearly
or smooth step.
> feat(Data): remap a float value from a range to another

- Runtime/Process/Moment/MomentProcessor.cs
This fixes the MomentProcessor to use correct events when a SRP is used
> fix(MomentProcessor): fix events to work correctly when a SRP is used

- Runtime/Process/Moment/MomentProcessor.cs
A compile error was occurring because Unity 2018 did not support the
SRP related calls outside of an experimental namespace. It's not a good
idea to support experimental Unity solutions so the fix for this
compile error is to just only support SRP on Unity 2019.1 and above as
the required functionality is standard in 2019.1 and above.
A warning will be logged if SRP is used on 2018.
> fix(Process): restrict SRP support to 2019.1 and above - fixes #424

- Runtime/Action/AllAction.cs
- Runtime/Action/AnyAction.cs
- Tests/Editor/Action/AllActionTest.cs
- Tests/Editor/Action/AnyActionTest.cs
If All/AnyAction references other actions that are destroyed,
it will generate null reference exception when all/any attempts to
remove listeners (when they are disabled or destroyed).
> fix(Action): all/anyAction references destroyed actions

- Runtime/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotation.cs
- Tests/Editor/Tracking/Follow/Modifier/Property/Rotation/TransformPositionDifferenceRotationTest.cs
The TransformPositionDifferenceRotation had an issue where if the
source and target GameObjects were descendants of another GameObject
that was also moving, then the source position and previous position
would be further away due to the move in their ancestor GameObject
causing the rotation calculation to be incorrect. This fix provides
the ability to inject the ancestor GameObject to ensure the calculation
is still correct.
> fix(Tracking): remove ancestor position when calculating rotation - fixes #429

- Editor/Data/Attribute/CustomInspectorTextAttributeDrawer.cs
- Editor/Data/Attribute/CustomInspectorTextAttributeDrawer.cs.meta
- Runtime/Data/Attribute/CustomInspectorTextAttribute.cs
- Runtime/Data/Attribute/CustomInspectorTextAttribute.cs.meta
The new CustomInspectorText attribute allows an inspector field to have
custom text instead of Unity using the field/property name for the
inspector text.
This only works with simple fields at the moment and does not work with
nested fields such as the ObservableList Drawer.
> feat(Attribute): provide custom inspector text for inspector properties - resolves #431

- Runtime/Association/GameObjectsAssociationActivator.cs
An exception error would occur if the Association list was set up
but contained empty elements, which is the default state for Unity.
This has been fixed by simply doing null checks before accessing data.
> fix(Association): perform null check before accessing associations

- Runtime/Tracking/Velocity/VelocityMultiplier.cs
- Tests/Editor/Tracking/Velocity/VelocityMultiplierTest.cs
*Breaking Change*
The VelocityMultiplier only allowed for a float to be multiplied
to the whole velocity vector making the multiplication very linear
and not able to affect different parts of the velocity by different
values.
This has now been changed so the multiplier is actually a Vector3,
meaning it can affect different elements with different multipliers.
This is also useful if a certain velocity axis wants to be removed
by simply multiplying that axis by 0.
> feat(Velocity): multiply velocity by vector rather than float

- Runtime/Process/Moment/CompositeProcess.cs
- Runtime/Process/Moment/CompositeProcess.cs.meta
- Tests/Editor/Process/Moment/CompositeProcessTest.cs
- Tests/Editor/Process/Moment/CompositeProcessTest.cs.meta
The CompositeProcess component allows to treat a
MomentProcessObservableList as an IProcessable.
This allows related moment processes to be organized
into a list and be nested in other list.
> feat(Moment): treats a given MomentProcess collection as IProcessable.

- Editor/Data/Attribute/RestrictedAttributeDrawer.cs
The `[Restricted]` attribute was using a standard `Color.gray` but this
became unreadable when using the Unity professional dark skin. A custom
grey color is now being used which is visible and readable in both the
professional and personal Unity skin.
> fix(Attribute): provide custom grey color for restricted muted option - fixes #373

- Editor/Data/Type/CollapsibleUnityEventDrawer.cs
The CollapsibleUnityEvent drawer Editor drawer was setting the scene
as dirty on first draw of the component which was then causing an error
in Unity 2019.1 and above when a prefab utilizing the custom drawer
was drawn in the inspector. This is because the prefab cannot be
saved if it is coming from a 3rd party Unity package and attempting
to set the scene as dirty was causing an attempt to save.
There is no reason for this SetDirty to occur as it provides no
required functionality so the line has been removed which should
fix the error it was causing.
> fix(Data): prevent collapsible event drawer from setting scene as dirty - fixes #440

- Tests/Editor/Data/Type/Transformation/Conversion/Vector2ToFloatTest.cs
Tests should not need to extend MonoBehaviour and this was causing a
warning to be displayed due to this test extending it. The fix is to
simply prevent the test class from extending MonoBehaviour.
> fix(Data): stop Vector2ToFloatTest extending MonoBehaviour

- Runtime/Tracking/Query/ObscuranceQuery.cs
The ObscuranceQuery logic was changed so the Target requires either a
Collider or if it has a Rigidbody then there must be at least 1 child
Collider.
The Exception messages we never updated so it provided inaccurate
information if the usage criteria was incorrect.
> fix(Tracking): update exception message in ObscuranceQuery - fixes #438

- Runtime/Tracking/Collision/CollisionTracker.cs
The CollisionTrackerDisabledObserver is now always added and removed
when a collision occurs rather than before where it was only added or
removed if that collision state was being listened to.
The previous way would cause the CollisionTrackerDisabledObserver to
either not be added at all or be added multiple times because it was
never being removed.
> fix(Collision): always add/remove the CollisionTrackerDisabledObserver - fixes #464

- Runtime/Pointer/ObjectPointer.cs
- Tests/Editor/Pointer/ObjectPointerTest.cs
The ObjectPointer can now disable the destination pointer element if
there is no collision data from the RayCast.
Also, the ObjectPointer test was incorrect as the pointer elements
were set up incorrectly where the container was assigned to the mesh
and vice versa. This has now been corrected and the tests updated
to reflect this change.
> feat(ObjectPointer): option to disable destination on no collision

- Runtime/Rule/StringInListRule.cs
The TryGetComponent method being used was not valid in 2018.3 and must
have been introduced in 2019.1.
The fix is to fallback to using the Zinnia.Extension version of the
TryGetComponent method.
> fix(Rule): allow StringInListRule to work in Unity 2018.3

- Runtime/Action/Action.cs
- Tests/Editor/Action/AllActionTest.cs
- Tests/Editor/Action/BooleanActionTest.cs
The new `ReceiveDefaultValue` method is a shortcut for the `Receive`
method but it simply makes the Action receive its own default value.
This can be used to programmatically get an Action to call its own
deactivation event if the Action is already activated without needing
to know the type of the concrete action. This is useful when dealing
with Actions in their generic abstract form but wanting them to
emit their deactivated state for whatever reason, such as a linked
GameObject becoming disabled.
> feat(Action): add method for action to receive its own default value

- Runtime/Tracking/Velocity/ComponentTrackerProxy.cs
This fix will cache velocity tracker for this component to work
when the ProxySource is set up in editor time.
> fix(Tracking): cache tracker source when OnEnable - fixes #486

- Runtime/Data/Collection/GameObjectRelations.cs
- Tests/Editor/Data/Collection/GameObjectRelationsTest.cs
The KeyNotFound event is raised whenever the GetValue method on the
GameObjectRelations component is called but no key can be matched
because either the key is not in the dictionary or the index given
is out of bounds of the collection.
> feat(Data): add KeyNotFound event to GameObjectRelations

- Runtime/Action/Action.cs
Having the ValueUnchanged event in the Sources chain does not make
sense as it causes the `any` concept of the Sources to fail because
the logic goes:
Has SourceA changed? no, then don't call Target.Receive
but SourceA is unchanged so call Target.Receive
Has SourceB changed? no, then don't call Target.Receive
but SourceB is unchanged so call Target.Receive
The above scenario would mean Target is still false, however:
Has SourceA changed? Yes, then call Target.Receive(true)
SourceA is changed so the second receive won't be called
Has SourceB changed? No, then don't call Target.Receive
SourceB is unchanged so call Target.Receive(false)
Now Target has gone from true to false causing it to reset its own
state.
Really, the Sources should only be used for actual change proxying
and not try to …
> fix(Action): remove unchanged event from being chained in sources

- Runtime/Data/Operation/Extraction/ValueExtractor.cs
The Source property from the ValueExtractor is of a generic type and
if the Cleared attribute is used then Malimbe will always weave an
auto generated Clear method that attempts to set the property to null
and this will cause issues in IL2CPP when attempting to clear non
nullable types such as RaycastHit.
As there is a manual ClearSource method already that sets Source to
`default` then this `Cleared` attribute can simply be removed.
> fix(Extraction): remove Cleared attribute from ValueExtractor.Source - fixes #498

- Runtime/Process/Moment/MomentProcessor.cs
- Runtime/Tracking/Follow/Modifier/Property/DivergablePropertyModifier.cs
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataSourceExtractor.cs
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataSourceExtractor.cs.meta
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetExtractor.cs
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetExtractor.cs.meta
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetOffsetExtractor.cs
- Runtime/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetOffsetExtractor.cs.meta
- Runtime/Tracking/Velocity/XRNodeVelocityEstimator.cs
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataSourceExtractorTest.cs
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataSourceExtractorTest.cs.meta
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetExtractorTest.cs
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetExtractorTest.cs.meta
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetOffsetExtractorTest.cs
- Tests/Editor/Tracking/Follow/Operation/Extraction/ObjectFollowerEventDataTargetOffsetExtractorTest.cs.meta
A collection of extractors that can extract specific data from
the ObjectFollower.EventData.
For example, an Interactable is using Follow Rigidbody.
When it is diverged, the event data can be feed into the
FollowerSourceExtractor to get the grabbing interactor.
> feat(Extraction): add extractors for ObjectFollower.EventData

- Runtime/Tracking/Collision/Active/ActiveCollisionConsumer.cs
- Runtime/Tracking/Collision/Active/ActiveCollisionPublisher.cs
- Runtime/Tracking/Collision/Active/ActiveCollisionRegisteredConsumerContainer.cs
- Runtime/Tracking/Collision/Active/ActiveCollisionRegisteredConsumerContainer.cs.meta
- Runtime/Tracking/Collision/Active/Event/Proxy/ActiveCollisionPublisherEventProxyEmitter.cs
- Runtime/Tracking/Collision/Active/Event/Proxy/ActiveCollisionPublisherEventProxyEmitter.cs.meta
- Runtime/Tracking/Collision/Active/Event/Proxy/ActiveCollisionRegisteredConsumerContainerEventProxyEmitter.cs
- Runtime/Tracking/Collision/Active/Event/Proxy/ActiveCollisionRegisteredConsumerContainerEventProxyEmitter.cs.meta
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerMock.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerMock.cs.meta
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionConsumerTest.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionPublisherTest.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionRegisteredConsumerContainerTest.cs
- Tests/Editor/Tracking/Collision/Active/ActiveCollisionRegisteredConsumerContainerTest.cs.meta
- Tests/Editor/Tracking/Collision/Active/Event/Proxy/ActiveCollisionPublisherEventProxyEmitterTest.cs
- Tests/Editor/Tracking/Collision/Active/Event/Proxy/ActiveCollisionPublisherEventProxyEmitterTest.cs.meta
- Tests/Editor/Tracking/Collision/Active/Event/Proxy/ActiveCollisionRegisteredConsumerContainerEventProxyEmitterTest.cs
- Tests/Editor/Tracking/Collision/Active/Event/Proxy/ActiveCollisionRegisteredConsumerContainerEventProxyEmitterTest.cs.meta
The ActiveCollisionRegisteredConsumerContainer is linked to a
ActiveCollisionPublisher and its job is to store a collection
of consumers that the publisher has successfully published to.
This means the publisher still doesn't know directly who it is
publishing to, but holds an audit log of which consumers have
successfully received the payload in the past.
The ActiveCollisionConsumer now also holds a reference to the
top level container (i.e. the colliding rigidbody/collider GameObject)
that the component is residing under.
> feat(Tracking): add container for successful published consumers

- Runtime/Haptics/TimedHapticProcess.cs
- Runtime/Haptics/XRNodeHapticPulser.cs
- Runtime/Tracking/CameraRig/LinkedAliasAssociationCollection.cs
The LinkedAliasAssociationCollection now has the concept of haptic
profiles for the left and right controller.
The haptic profile is a list of haptice processes for each controller
that describe different haptic output scenarios.
> feat(Tracking): add haptic profiles to LinkedAliasAssociationCollection

- Runtime/Tracking/Follow/Modifier/Property/Rotation/RigidbodyAngularVelocity.cs
The RigidbodyAngularVelocity component was calculating the angle of
angular velocity in degrees but angular velocity is set in radians
so this was causing artifacts when rotating.
The fix is to ensure the angle is calculated in radians.
Co-authored-by: JGroxz
> fix(Tracking): calculate angular velocity angle in radians

- Runtime/Tracking/Follow/Modifier/Property/Rotation/RotateAroundAngularVelocity.cs
When using an angular transform drive as a handleless door knob,
this class is used to track the interactor's "wrist" rotation,
but as it is now the this only works when drive/interactor are
aligned with world space.  By using this new option, the angular
velocity will be transformed to the target's space, and thus
applied properly.
> feat(Tracking): allow local space rotation around angular velocity

- Editor/Utility/BasePrefabCreator.cs
The Prefab Creator has now been moved to the `GameObject` main menu
so it can also show up in the right click context menu for adding
new items to the hierarchy.
> fix(Utility): move prefab creator menu location

- Runtime/Tracking/Collision/CollisionNotifier.cs
- Runtime/Tracking/Collision/CollisionTracker.cs
The CollisionTracker component now has a Collider Validity rule to
determine whether it can emit collisions of the collider that is being
collided with passes the validity rule check.
Headers have been added to the properties for better separation in the
Unity editor.
> feat(Tracking): add collider validity rule to collision notifier

- Runtime/Tracking/Collision/CollisionNotifier.cs
- Runtime/Visual/CameraColorOverlay.cs
The methods responsible for handling collision events in the
CollisionNotifier have been made public so they can be called manually
if need be.
This is useful if a manual collision is needed to be raised without an
actual physics collision taking place to simulate collisions.
> feat(Tracking): publicize collision notifier collision methods

- Runtime/Tracking/Collision/CollisionTracker.cs
- Tests/Editor/Tracking/Collision/CollisionTrackerTest.cs
There was an issue with the 2019 kinematic fix where if a GameObject
with multiple child colliders was touched on one collider and then
when the kinematic state changed the collider would no longer be
touched but another collider in the GameObject was touched then the
exit event would not happen for the original collider and the new
start event for the new collider would not happen.
This would mean the collision with the original collider would have
ended in the CollisionTracker but the CollisionTracker would not
have reported it, and the new collider collision would not have a
started event reported. Then when the actual new collider collision
ended it would not report it had ended correctly.
The fix is to hold a dictionary for each collider and their frame
interaction timestamp and then …
> fix(Tracking): ensure right trigger exit happens on kinematic change

- Editor/Data/Collection/ObservableListEditor.cs
- Runtime/Tracking/Collision/CollisionTracker.cs
Unity have fixed a bug in Unity 2020.3.24f to do with reorderable lists
but that fix has caused the custom observable list editor to no longer
display any of the elements of the list and no longer understands if
the list is collapsible or not.
I can't be bothered to put the effort in to find out what Unity have
done or where this has broken, it's a constant struggle of chasing
after Unity changes so instead the feature of custom list editors
is now just disabled for Unity 2020.3 and above.
It can be added back in with a custom script define symbol of:
* `ZINNIA_USE_CUSTOM_LIST_EDITOR`
This will make the custom list editor appear again, however it will
no longer be a collapsible element.
The custom list editor can also now be completely disabled by using
the script define symbol of:
* …
> fix(Collection): remove custom list editor for Unity 2020.3 or newer

- Runtime/Pattern/XRDevicePatternMatcher.cs
- Runtime/Utility/XRDeviceProperties.cs
- Runtime/Utility/XRDeviceProperties.cs.meta
The XRDevice properties that differ between Unity versions due to
elements being made obsolete were originally included directly in
the XRDevicePatternMatcher component. But this logic is useful in
more places so it has been abstracted out into a Utility class that
is static so it can be called from any other component requiring
this abstraction.
It also includes the checks for IsTracked, BatteryLevel, Manufacturer
(even though they only work on Unity 2019.3 and above).
The XRDevicePatternMatcher can also now specify which device node
to look up the details for as on Unity 2019.3 and above the device
can be specified in the look up. This does not work on versions
prior to Unity 2019.3.
> feat(Utility): abstract XRDevice queries to static class

- Runtime/Pattern/XRDevicePatternMatcher.cs
- Runtime/Utility/XRDeviceProperties.cs
The XRDeviceProperties class now returns data for:
* DeviceCount
* HasPositionalTracking
* HasRotationalTracking
* IsValid (but only for 2019.3 and above)
It also has a couple of new methods that are only available in 2019.3
and above:
* DeviceInstance
* IsDeviceDefault
The XRDevicePatternMatcher has been updated to match against these new
properties and it can also set the XRNode device source now via a
method.
> feat(Utility): add extra abstracted XRDevice properties

- Runtime/Action/SurfaceChangeAction.cs
- Runtime/Data/Type/SurfaceData.cs
- Runtime/Tracking/SurfaceLocator.cs
- Tests/Editor/Action/SurfaceChangeActionTest.cs
The Surface Change Action actually needs to access the offset that the
SurfaceLocator has on it, but there is no way of directly getting this
so the SurfaceData has now been updated to contain a Positional Offset
property that can be set by the Surface Locator and then accessed by
the Surface Change Action.
> feat(Action): allow access to surface locator destination offset

- Editor/Data/Type/DefaultObservableListDrawer.cs
The Observable List Drawer has an issue in Unity 2021.2 where making
changes to a linked list will not save due to the way the serialized
object is obtained as new every frame, this means that the object
can be out of date and load in the old changes.
This also was a cause of an issue where having the linked list
component on the same component as the actual list meant it would not
save changes.
The fix is to only get the new version of the serialized list object
if any changes have been made and therefore it won't attempt to get
it every frame.
> fix(Data): allow list drawer to save changes

- Runtime/Visual/CameraColorOverlay.cs
The deltaTime and WaitForSeconds get affected by the time scale
which can cause the overlay to never fade in or out when time scale
is set to approximately 0. Switching to unscaledDeltaTime and
WaitForSecondsRealtime will always fade in and out no matter
the time scale.
> fix(CameraOverlay): change scaled time to unscaled time

- Runtime/Tracking/Follow/Modifier/Property/Position/RigidbodyVelocity.cs
- Runtime/Tracking/Velocity/VelocityApplier.cs
Rigidbodies cannot have velocities set on them if they are kinematic as they are not actually part of the physics simulation when kinematic so this fix just ensures the kinematic state is checked before trying to apply a velocity to a rigidbody.
> fix(Tracking): ensure velocity is not set on kinematic rigidbody

- Editor/Utility/ScenePipelineMaterialApplier.cs
- Editor/Utility/ScenePipelineMaterialApplier.cs.meta
- Runtime/Utility/PipelineMaterialApplier.cs
- Runtime/Utility/PipelineMaterialApplier.cs.meta
The PipelineMaterialApplier will set the Materials on a given Renderer based on the current render pipeline being used. It gets the materials to apply from a given list of materials that has a string group name that matches the desired render pipeline name.
If no render pipeline is provided then the matched name will be:
* `default`
There is also an editor menu item that will attempt to find all PipelineMaterialApplier components in the scene and run them to ensure all materials on the renderers are updated to match the current render pipeline.
> feat(Utility): add pipeline material applier component

- Runtime/Data/Operation/Mutation/TransformEulerRotationMutator.cs
- Runtime/Data/Operation/Mutation/TransformPositionMutator.cs
- Runtime/Data/Operation/Mutation/TransformPropertyMutator.cs
- Runtime/Data/Operation/Mutation/TransformScaleMutator.cs
- Runtime/Utility/PipelineMaterialApplier.cs
- Tests/Editor/Data/Operation/Mutation/TransformPositionMutatorTest.cs
The PipelineMaterialApplier component now has another option to determine what render pipeline is being used. The default Pipeline Shader name can also be provided to determine which render pipeline is active as sometimes the name is not robust enough as it can be renamed in the settings.
> feat(Utility): allow pipeline shader to select material

- Runtime/Event/Proxy/BooleanEventProxyEmitter.cs
- Runtime/Event/Proxy/BooleanEventProxyEmitter.cs.meta
- Tests/Editor/Event/Proxy/BooleanEventProxyEmitterTest.cs
- Tests/Editor/Event/Proxy/BooleanEventProxyEmitterTest.cs.meta
A new Proxy Emitter has been added for Boolean data types to easily allow chaining and proxying boolean data types.
> feat(Proxy): add boolean event proxy emitter
