ExtendRealityLtd/Zinnia.Unity

- Tests/Editor/Extension.meta
- Tests/Editor/Extension/ComponentExtensionsTest.cs
- Tests/Editor/Extension/ComponentExtensionsTest.cs.meta
The ComponentExtensions now have some unit tests.
> chore(Extension): add tests for component extensions

- Tests/Editor/Tracking/Follow/ObjectFollowTest.cs
- Tests/Editor/Tracking/TransformModifyTest.cs
- Tests/Editor/Visual.meta
- Tests/Editor/Visual/CameraColorOverlayTest.cs
- Tests/Editor/Visual/CameraColorOverlayTest.cs.meta
A number of unit test files were not testing the events. This commit
adds a number of tests to check the events are emitted correctly.
> chore(testing): add event tests - fixes #76

- Scripts/Pointer/ObjectPointer.cs
The ObjectPointer was relying on the `previousPointsCastData` to
determine if the target was no longer valid and was setting this
to null if the cast had exited a valid target.
However, it can never be null otherwise invalid casting doesn't
work. This fix removes the reliance on `previousPointsCastData`
and introduces a simple `isHovering` bool that determines if
the beam is currently over a valid target.
> fix(Pointer): remove reliance on cast data for invalid state

- Scripts/Pointer/ObjectPointer.cs
The ObjectPointer `Deactivated` event would always be called even if
the pointer component was disabled. This has been fixed by wrapping
the `Deactivate` method with an `isActiveAndEnabled` but also in the
`OnDisable` a specific `Deactivated` event is emitted otherwise the
event would never fire when the component is disabled at runtime.
Also, the hover duration was being reset to 0 before the exit event
was emitted meaning the exit event didn't include the correct hover
duration.
> fix(Pointer): ensure exit/deactivate events are called in correct order

- Scripts/Utility/BehaviourEnabledSetter.cs
- Scripts/Utility/BehaviourEnabledSetter.cs.meta
- Tests/Editor/Utility/BehaviourEnabledSetterTest.cs
- Tests/Editor/Utility/BehaviourEnabledSetterTest.cs.meta
A new type has been added helping with enabling or disabling all
components on a game object that match a particular type.
>  feat(Utility): disable or enable components by type - resolves #28

- Prefabs/Interactions/Interactors/SharedResources/Scripts/InteractorFacade.cs
The documentation was incorrect on the InteractorFacade and mentioned
things that were not relevant or just wrong.
> chore(Interaction): update InteractorFacade documentation

- Scripts/Action/AnyAction.cs
- Scripts/Action/AnyAction.cs.meta
- Tests/Editor/Action/AnyActionTest.cs
- Tests/Editor/Action/AnyActionTest.cs.meta
The AnyAction emits true when any of the given actions are
true, and will only emit false when all the actions are false.
> feat(Action): add any compound action

- Prefabs/Locomotion/Movement/AxesToVector3/AxesToVector3.prefab
- Prefabs/Locomotion/Movement/AxesToVector3/SharedResources/Scripts/AxesToVector3Facade.cs
- Prefabs/Locomotion/Movement/AxesToVector3/SharedResources/Scripts/AxesToVector3InternalSetup.cs
- Scripts/Data/Type/Transformation/FloatToBoolean.cs
- Scripts/Data/Type/Transformation/Transformer.cs
- Scripts/Data/Type/Transformation/Vector2ToVector3.cs
- Scripts/Data/Type/Transformation/Vector3ToVector2.cs
- Scripts/Data/Type/Transformation/Vector3ToVector2.cs.meta
- Scripts/Event/FloatEventProxyEmitter.cs
- Scripts/Event/FloatEventProxyEmitter.cs.meta
- Tests/Editor/Data/Type/Transformation/Vector3ToVector2Test.cs
- Tests/Editor/Data/Type/Transformation/Vector3ToVector2Test.cs.meta
- Tests/Editor/Event/FloatEventProxyEmitterTest.cs
- Tests/Editor/Event/FloatEventProxyEmitterTest.cs.meta
The AxesToVector3 prefab now has the ability to accept a direction on
a given axis and to move a specified distance on the first detection
of that axis direction.
This will enable the concept of warp walking, where the joystick input
is moved in a direction and on the first push it will move the player
forward a specified amount of position with a blink transition.
> feat(Locomotion): ability to move a set distance in a given direction - fixes #46 - fixes #47

- README.md
The Getting Started steps provide a step by step guide of how to
import VRTK.Unity.Core into an existing Unity3d project.
> docs(README.md): add getting started steps

- Runtime/Tracking/Modification/TransformPropertyApplier.cs
The TransformPropertyApplier could get into a situation where the
elapsed time would be a significantly small enough number away from the
transition duration to prevent the lerp from actually finishing and
would continue to update the properties of the transform by a very tiny
amount.
This fix adds a new threshold to check that the start and destination
properties of the transform scale, rotation and position are considered
equal to force the transition coroutine to finish and set the
properties to their final destination values.
> fix(Modification): add threshold to destination equality check on lerp

- Runtime/Data/Type/Transformation/Vector3Restrictor.cs
- Runtime/Data/Type/Transformation/Vector3Restrictor.cs.meta
- Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs
- Tests/Editor/Data/Type/Transformation/Vector3RestrictorTest.cs.meta
The Vector3Restrictor allows the clamping of Vector3 values based on
specified bounds.
> feat(Transformation): ability to restrict the values of a Vector3

- Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs
- Runtime/Tracking/Velocity/ArtificialVelocityApplier.cs.meta
- Runtime/Tracking/Velocity/VelocityApplier.cs
The ArtificialVelocityApplier mimics rigidbody velocities by applying
directional and rotational data to a Transform giving the impression
the object is moving with applied velocity. It also has the ability
to apply opposing drag forces to slow the velocity down over time.
> feat(Velocity): ability to apply artificial velocities to an object

- README.md
Instructions have been added that give a step by step guide of
how to run the playmode tests.
A few spelling mistakes have been fixed also.
> docs(README.md): add instructions of how to run the tests

- Runtime/Data/Type/Transformation/CollectionAggregator.cs
- Runtime/Data/Type/Transformation/Vector2Multiplier.cs
- Runtime/Data/Type/Transformation/Vector3Multiplier.cs
- Runtime/Haptics/AudioClipHapticPulser.cs
- Runtime/Pointer/ObjectPointer.cs
- Runtime/Pointer/PointerElement.cs
- Runtime/Rule/RulesMatcher.cs
- Runtime/Tracking/Follow/ObjectFollower.cs
- Runtime/Tracking/Query/ObscuranceQuery.cs
- Runtime/Visual/CameraColorOverlay.cs
- Tests/Editor/Tracking/Collision/CollisionIgnorerTest.cs
Wrong references in XML documentation or missing ones altogether
have been fixed in this change in both the component files as well
as the tests.
> chore(general): fix invalid XML documentation comments

- Editor/Utility/InterfaceContainerDrawer.cs
The component picker draws an object field and then has to check how
that field was interacted with. Because the only public API offered
by Unity always creates an instance of the internal `ObjectSelector`
window that window could linger around in the editor, which resulted
in an error being logged whenever the game view was maximized. The
fix is to work around the internal logic of this API and instead use
intrinsic knowledge about how the internals works to figure out
whether a drop of a dragged object happened, or whether the picker
window was closed.
> fix(Utility): error log when drawing field for component picker

- Runtime/Tracking/SurfaceLocator.cs
- Tests/Editor/Tracking/SurfaceLocatorTest.cs
A new `LocatorTermination` Rule has been added to the SurfaceLocator
that allows a given rule to determine if the locator hits a target
which matches the rule to simply terminate the locator operation and
no longer continue to search for a valid surface.
This is in addition to the `TargetValidity` Rule which will ignore
invalid targets but continue searching for the next valid target. The
`LocatorTermination` Rule will prevent this search from continuing.
> feat(Tracking): terminate surface locator on certain collisions - fixes ExtendRealityLtd/VRTK#2012

- Editor/Data/Type/DefaultObservableListDrawer.cs
- Editor/Data/Type/DefaultObservableListDrawer.cs.meta
- Runtime/Data/Collection/List/ObservableList.cs
The ObservableList component will now display the reference object in
the inspector and when the reference is populated it will display the
elements collection inline underneath the reference object making
updating ObservableList elements much easier.
> feat(Type): display observable list elements inline in inspector

- Runtime/Visual/CameraColorOverlay.cs
The CameraColorOverlay now has additional events and state for whether
the overlay is currently in an Add or Remove transition and it emits
an event when it reaches the end of either the Add or Remove transition
state with the existing Added/Removed events being there to signal when
the transition process was initiated.
The Added/Removed event names aren't ideal but changing them will
introduce an unwanted breaking change which doesn't seem worth it
right now.
> feat(Visual): add events for transitioned state of overlay - fixes #406

- Runtime/Data/Type/Transformation/Conversion/Vector2ToFloat.cs
- Runtime/Data/Type/Transformation/Conversion/Vector2ToFloat.cs.meta
- Tests/Editor/Data/Type/Transformation/Conversion/Vector2ToFloatTest.cs
- Tests/Editor/Data/Type/Transformation/Conversion/Vector2ToFloatTest.cs.meta
The Vector2ToFloat allows a Vector2 coordinate to be extracted and
converted to a float value.
> feat(Transformation): convert a vector2 coordinate to a float

- Runtime/Tracking/SurfaceLocator.cs
- Tests/Editor/Tracking/SurfaceLocatorTest.cs
> fix(Tracking): Teleport snap to floor incorrect

- Runtime/Data/Type/Transformation/Conversion/FloatToVector3.cs
- Runtime/Data/Type/Transformation/Conversion/FloatToVector3.cs.meta
- Tests/Editor/Data/Type/Transformation/Conversion/FloatToVector3Test.cs
- Tests/Editor/Data/Type/Transformation/Conversion/FloatToVector3Test.cs.meta
The FloatToVector3 component allows to transform a float array
to a Vector3.
> feat(Data): transform float to Vector3

- Runtime/Process/EventProcess.cs
- Runtime/Process/EventProcess.cs.meta
Allows to call any no argument methods for a given moment.
> feat(Process): a IProcessable that emits event when processed.

- Runtime/Haptics/AudioClipHapticPulser.cs
- Runtime/Haptics/AudioSourceHapticPulser.cs
- Runtime/Haptics/AudioSourceHapticPulser.cs.meta
- Runtime/Haptics/RoutineHapticPulser.cs
- Runtime/Haptics/RoutineHapticPulser.cs.meta
This haptic generated reflects the current playing audio even if
the audio is looping, delayed, volume/pitch modulated.
> feat(Haptics): create haptic pattern based on AudioSource

- Runtime/Utility/CountdownTimer.cs
- Tests/Editor/Utility/CountdownTimerTest.cs
The CountdownTimer now has RequestElapsedTime and RequestRemainingTime methods
which emit the ElapsedTime and RemainingTime of the timer.
> feat(Utility): provide remaining and elapsed time when requested

- Runtime/Data/Type/Transformation/Conversion/Vector2ToFloat.cs
- Runtime/Data/Type/Transformation/Conversion/Vector3ToFloat.cs
- Runtime/Data/Type/Transformation/Conversion/Vector3ToFloat.cs.meta
- Runtime/Tracking/Velocity/VelocityEmitter.cs
- Tests/Editor/Data/Type/Transformation/Conversion/Vector2ToFloatTest.cs
- Tests/Editor/Data/Type/Transformation/Conversion/Vector3ToFloatTest.cs
- Tests/Editor/Data/Type/Transformation/Conversion/Vector3ToFloatTest.cs.meta
- Tests/Editor/Tracking/Velocity/VelocityEmitterTest.cs
> feat(Data): add properties to extract float from Vector2 and Vector3

- Runtime/Utility/AnimatorParameterMutator.cs
- Runtime/Utility/AnimatorParameterMutator.cs.meta
- Runtime/Utility/AnimatorScrubber.cs
- Runtime/Utility/AnimatorScrubber.cs.meta
- Tests/Editor/Utility/AnimatorParameterMutatorTest.cs
- Tests/Editor/Utility/AnimatorParameterMutatorTest.cs.meta
- Tests/Editor/Utility/AnimatorScrubberTest.cs
- Tests/Editor/Utility/AnimatorScrubberTest.cs.meta
- Tests/TestResources.meta
- Tests/TestResources/Animation.meta
- Tests/TestResources/Animation/TestAnimation.anim
- Tests/TestResources/Animation/TestAnimation.anim.meta
- Tests/TestResources/Animation/TestAnimatorController.controller
- Tests/TestResources/Animation/TestAnimatorController.controller.meta
The AnimatorScrubber component allows an animation timeline to be scrubbed through by providing the exact normalized timestamp to jump the animation to.
The AnimatorParameterMutator allows the mutation of parameters assigned to an Animation Controller.
> feat(Utility): add animation helper components
